"""init

Revision ID: 174c6e33a570
Revises: 
Create Date: 2026-05-03 15:45:58.721453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174c6e33a570'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.alter_column('bin_metadata', 'bin_unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_bin_metadata_id'), 'bin_metadata', ['id'], unique=False)
    op.create_foreign_key(None, 'bin_metadata', 'bin_units', ['bin_unit_id'], ['id'])
    op.alter_column('bin_units', 'unit_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bin_units', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bin_units', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('bin_units', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('officers', 'officer_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('officers', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('officers', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('officers', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('officers_email_key', 'officers', type_='unique')
    op.drop_constraint('officers_officer_id_key', 'officers', type_='unique')
    op.create_index(op.f('ix_officers_email'), 'officers', ['email'], unique=True)
    op.create_index(op.f('ix_officers_id'), 'officers', ['id'], unique=False)
    op.create_index(op.f('ix_officers_officer_id'), 'officers', ['officer_id'], unique=True)
    op.alter_column('tasks', 'task_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('tasks', 'bin_unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'worker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('tasks_task_id_key', 'tasks', type_='unique')
    op.create_index(op.f('ix_tasks_bin_unit_id'), 'tasks', ['bin_unit_id'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=True)
    op.create_index(op.f('ix_tasks_worker_id'), 'tasks', ['worker_id'], unique=False)
    op.alter_column('workers', 'worker_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('workers', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('workers', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('workers', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('workers', 'zone',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_constraint('workers_email_key', 'workers', type_='unique')
    op.drop_constraint('workers_worker_id_key', 'workers', type_='unique')
    op.create_index(op.f('ix_workers_email'), 'workers', ['email'], unique=True)
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    op.create_index(op.f('ix_workers_worker_id'), 'workers', ['worker_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workers_worker_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_email'), table_name='workers')
    op.create_unique_constraint('workers_worker_id_key', 'workers', ['worker_id'])
    op.create_unique_constraint('workers_email_key', 'workers', ['email'])
    op.alter_column('workers', 'zone',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('workers', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('workers', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('workers', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('workers', 'worker_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_tasks_worker_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_bin_unit_id'), table_name='tasks')
    op.create_unique_constraint('tasks_task_id_key', 'tasks', ['task_id'])
    op.alter_column('tasks', 'worker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'bin_unit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'task_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_officers_officer_id'), table_name='officers')
    op.drop_index(op.f('ix_officers_id'), table_name='officers')
    op.drop_index(op.f('ix_officers_email'), table_name='officers')
    op.create_unique_constraint('officers_officer_id_key', 'officers', ['officer_id'])
    op.create_unique_constraint('officers_email_key', 'officers', ['email'])
    op.alter_column('officers', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('officers', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('officers', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('officers', 'officer_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('bin_units', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('bin_units', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('bin_units', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bin_units', 'unit_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'bin_metadata', type_='foreignkey')
    op.drop_index(op.f('ix_bin_metadata_id'), table_name='bin_metadata')
    op.alter_column('bin_metadata', 'bin_unit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('zone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('green_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('streak', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kg_diverted', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('co2_saved', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('disposals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    # ### end Alembic commands ###
